sudo: required
dist: trusty

language: node_js
node_js:
  - "4"

env:
  global:
    - GITHUB_OAUTH_KEY=003a44d58f12089d0c0261338298af3813330949

branches:
  except:
    - /^greenkeeper-.+$/

cache:
  yarn: true
  directories:
    - node_modules
    - broccoli-persistent-cache

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm i -g yarn
  - yarn global add bower
  - yarn
  - bower install
  - cd lib/ghost-editor && yarn && bower install

before_script:
  - yarn add --force node-sass # temporary, workaround for https://github.com/yarnpkg/yarn/issues/1981
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3;
  - export BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT=/home/travis/build/TryGhost/Ghost-Admin/broccoli-persistent-cache

script:
  - COVERAGE=true npm test

after_success:
  - npm run coverage
