sudo: required
dist: trusty

language: node_js
node_js:
  - "4"

env:
  global:
    - GITHUB_OAUTH_KEY=003a44d58f12089d0c0261338298af3813330949

branches:
  except:
    - /^greenkeeper-.+$/

cache:
  directories:
    - node_modules

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - google-chrome-stable
      - yarn

install:
  - yarn global add bower
  - yarn
  - bower install

before_script:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3;

script:
  - COVERAGE=true npm test

after_success:
  - npm run coverage
