dist: xenial
language: node_js
node_js:
- '10'
- '12'
cache: yarn
env:
  global:
  - MOZ_HEADLESS=1
  - JOBS=1
# Don't run builds for renovate PRs
if: NOT head_branch =~ ^renovate
addons:
  firefox: latest
  chrome: stable
install:
- yarn
script:
- yarn run lint:js && yarn run test
after_failure: |
  if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
    curl -X POST --data-urlencode "payload={\"attachments\": [{\"color\": \"danger\", \"fallback\": \"Build Failure: $TRAVIS_JOB_WEB_URL\", \"title\": \"Build Failure\", \"text\": \"$TRAVIS_JOB_WEB_URL\"}]}" $SLACK_URL
  fi
