sudo: required
dist: trusty

language: node_js
node_js:
  - "4"

env:
  global:
    - GITHUB_OAUTH_KEY=003a44d58f12089d0c0261338298af3813330949
    - JOBS=1 # See https://git.io/vdao3 for details.

branches:
  except:
    - /^greenkeeper-.+$/

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bower's cache

addons:
  firefox: "latest"
  chrome: "stable"

before_install:
  # install latest yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn global add bower
  - yarn
  - bower install

before_script:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3;

script:
  - COVERAGE=true npm test

after_success:
  - npm run coverage
