language: node_js
node_js:
  - "4"

env:
  global:
    - GITHUB_OAUTH_KEY=003a44d58f12089d0c0261338298af3813330949
    - SAUCE_USERNAME=acburdine
    - SAUCE_ACCESS_KEY=970dd0ed-3446-42f1-a49a-83bc951975e0

matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=lint

branches:
  except:
    - /^greenkeeper-.+$/

cache:
  directories:
    - node_modules

before_install:
  - npm config --global set spin false
  - npm install -g npm@^2

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - if [ "$TEST_SUITE" != "lint" ]; then ember sauce:connect; fi

script:
  - if [ "$TEST_SUITE" == "lint" ]; then grunt lint; else npm test -- --test-port 7000 --config-file testem.sl.js; fi

after_script:
  - if [ "$TEST_SUITE" != "lint" ]; then ember sauce:disconnect; fi
