sudo: required
dist: trusty

language: node_js
node_js:
  - "0.10"

matrix:
  include:
    - node_js: "0.10"
      env: TEST_SUITE=lint

cache:
  directories:
    - node_modules

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm config --global set spin false
  - npm install -g npm@^2

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3;

script:
  - if [ "$TEST_SUITE" == "lint" ]; then grunt lint; else npm test; fi
